name: Setup Build Environment

inputs:
  pythonVersion:
    description: Version of Python
    required: true
    default: '3.x'
    
  NodeJSVersion:
    description: Version of NodeJS
    required: false
    default: '18.x'

outputs:
  repoOwner:
    description: "Repository Owner"
    value: ${{ steps.vars.outputs.RepositoryOwner }}
  DefaultBranch:
    description: "Default Branch"
    value: ${{ steps.vars.outputs.DefaultBranch }}
  CICDKey:
    description: "CICD Key"
    value: ${{ steps.vars.outputs.CICDKey }}
    

    
runs:
  using: "composite"

  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Variables
      id: vars
      shell: bash #pwsh for Powershell
      run: |
        echo "RepositoryOwner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "DefaultBranch=main" >> $GITHUB_OUTPUT
        echo "CICDKey=ManojCICDKey" >> $GITHUB_OUTPUT
